class_name Characters
extends Object

static func load_cards() -> Array[CardCharacter]:
	return [
		PirateTwoTwoTwo.new(),
		Dwarf.new(1),
		Dwarf.new(2),
		Dwarf.new(3),
		Dwarf.new(4),
		Dwarf.new(5),
		Dwarf.new(6),
		Dwarf.new(7),
		DogOneOneOneOne.new(),
		Neighbors.new([3, 6]),
		Neighbors.new([4, 5]),
		GoblinXX.new(),
		GoblinXX.new(),
		GoblinXX.new(),
		KerberosXXX.new(),
		KerberosXXX.new(),
		EntXXXX.new(),
		NeighborXXYY.new(),
		Bilbo.new(true, "bilbo-even"),
		Bilbo.new(false, "bilbo-even"),
		PipeXXSixSix.new(),
		PipeXXSixSix.new(),
		VikingSixSixEightEight.new(),
		VikingSixSixEightEight.new(),
		BombadilSevenSevenEightEight.new(),
		BombadilSevenSevenEightEight.new(),
		TwinsEightEight.new(),
		TwinsEightEight.new(),
		UnicornOneTwoThreeFour.new(),
		MotherSevenSevenSevenSeven.new(),
		MotherSevenSevenSevenSeven.new(),
		LionEightEightEightEight.new(),
		PhoenixOneTwo.new(),
		PhoenixOneTwo.new(),
		TarzanTwenty.new(),
		ApeTen.new(),
		ApeTen.new(),
		ApeTen.new(),
		Actions.new([1, 3, 5, 7]),
		Actions.new([2, 4, 6, 8]),
		RedhoodFourFiveSixSevenEight.new(),
		EightForOne.new(),
		TomcatThreeFourFive.new(),
		ReaperOneEight.new(),
		PeekFiveSixSeven.new(),
		PeekFiveSixSeven.new(),
		DiscardSeven.new(),
		DiscardSeven.new(),
		DiamondForTwo.new(),
		ExchangeStreet.new(),
		PeekStack.new(),
		DiamondsSubtract.new(),
		ThreeForWildcard.new(),
	]
